apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.metadata.name }}
  labels:
    app: {{ .Values.metadata.labels.app }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      app: {{ .Values.metadata.labels.app }}
  template:
    metadata:
      labels:
        app: {{ .Values.metadata.labels.app }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: {{ .Chart.Name }}
              containerPort: {{ .Values.service.port }}
          env:
          - name: POSTGRES_USER
            value: {{ .Values.env.POSTGRES_USER }}
          - name: POSTGRES_PASSWORD
            value: {{ .Values.env.POSTGRES_PASSWORD }}
          volumeMounts:
          - mountPath: {{ .Values.Volume.mountPath }}
            name: {{ .Values.metadata.labels.app }}-data
      volumes:
        - name: {{ .Values.metadata.labels.app }}-data
          emptyDir: {}
